  version: 2.1
  jobs:
    build:
      docker: 
        - image: gemerick/frc2019:latest # the primary container, where your job's commands are run
      working_directory: /
      steps:
        - checkout # check out the code in the project directory
        - run:
          command: |
            echo Running build
            ./gradle clean build
