  version: 2.1
  jobs:
    build:
      docker: 
        - image: gemerick/frc2019:latest # the primary container, where your job's commands are run
      working_directory: /src
      steps:
        - checkout: # check out the code in the project directory
            path: /src
        - run:
            command: |
              echo Running build
              ./gradlew clean build
        - store_artifacts:
            path: /src/build/exe/frcUserProgram/release
